In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = np.arange(48).reshape(3, 4, 4, 1)

In [6]:
a = tf.convert_to_tensor(a, dtype=tf.float32)
a

<tf.Tensor: shape=(3, 4, 4, 1), dtype=float32, numpy=
array([[[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [ 7.]],

        [[ 8.],
         [ 9.],
         [10.],
         [11.]],

        [[12.],
         [13.],
         [14.],
         [15.]]],


       [[[16.],
         [17.],
         [18.],
         [19.]],

        [[20.],
         [21.],
         [22.],
         [23.]],

        [[24.],
         [25.],
         [26.],
         [27.]],

        [[28.],
         [29.],
         [30.],
         [31.]]],


       [[[32.],
         [33.],
         [34.],
         [35.]],

        [[36.],
         [37.],
         [38.],
         [39.]],

        [[40.],
         [41.],
         [42.],
         [43.]],

        [[44.],
         [45.],
         [46.],
         [47.]]]], dtype=float32)>

In [8]:
tf.math.reduce_max(tf.math.reduce_max(a, axis=1), axis=1)

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[15.],
       [31.],
       [47.]], dtype=float32)>